### ISSUE TITLE
自定义科大讯飞模块，初始化失败

### ISSUE THREAD

**Issue by DalesDawson** [yuanbao15/ModuleDevelop#3]
自定义科大讯飞模块，上传到apicloud网站后，调用显示初始化失败，请问一下，你知道为什么嘛

**Comment by yuanbao15** [comment]
需要看具体报错信息。
前提操作：自己在科大讯飞上创建账号、创建项目、添加服务、下载相关的jet文件、库包文件等替换。
先在这个app测试ok后再考虑打包模块上传到apicloud上。

**Comment by DalesDawson** [comment]
我在本地测试app里面都是对的，打包上传到apicloud上面，require后，调用方法就报错，VoiceWakeuper mIvw = VoiceWakeuper.getWakeuper(); 显示是这个对象初始化失败，mIvw 是null的，不知道是不是我打包的问题

**Comment by yuanbao15** [comment]
需要看具体报错信息。
你的模块上传后，添加进项目，打包自定义loader都是正常了么？

**Comment by DalesDawson** [comment]
解决了，是打包zip里面文件没放对，谢谢你
